# Gin is the web framework
gin:
  # Possible values: "debug", "release"
  mode: release
  # App running behind a reverse proxy?
  # If set, HTTP Forwarded headers will be respected
  reverse_proxy: false

# [BNB] Binance DEX: https://wallet.binance.org
#       Binance Chain: https://explorer.binance.org
binance:
  api: https://explorer.binance.org/api/v1

# [NIM] Nimiq: https://nimiq.com
#nimiq:
#  api: http://localhost:8648

# [XRP] Ripple: https://ripple.com
ripple:
  api: https://data.ripple.com/v2

# [XLM] Stellar Lumen: https://www.stellar.org
stellar:
  api: https://horizon.stellar.org

# [KIN] Kin: https://www.kin.org
kin:
  api: https://horizon.kinfederation.com

# [XTZ] Tezos: https://tezos.com
tezos:
  api: https://api1.tzscan.io/v3

# [ETH] Ethereum: https://ethereum.org (Trust-Ray API)
#ethereum:
#  api: https://localhost:4567

# [AION] Aion: https://aion.network
aion:
  api: https://mainnet-api.aion.network/aion/dashboard

# [ICX] ICON: https://icon.foundation
icon:
  api: https://tracker.icon.foundation/v3

# [TRX] Tron:
#tron:
#  api: https://api.trongrid.io/v1
#  token: my-access-token
