port: 8080
gin:
  mode: release

platforms:
  - binance
  - nimiq
  - ripple

binance:
  api: https://binance-rpc.trustwalletapp.com/v1

nimiq:
  rpc: https://nimiq-rpc.trustwalletapp.com/v1

ripple:
  api: https://data.ripple.com/v2
