# Gin is the web framework
gin:
  mode: release

# If all - run all platforms in one binary. You can pick specific coin handle to run binary only with specific coin
# Example: ethereum
# You can see all the coin handles at coins/coins.yml file
platform: all

spam_words: [ "airdrop","www", "http" ]

# The transaction watcher
observer:
  backlog: 3h
  # Don't request more than N blocks at once
  backlog_max_blocks: 200
  # Max connections to open to API
  stream_conns: 16
  # Block polling interval
  block_poll:
    min: 3s
    max: 30s
  rabbitmq:
    uri: amqp://rabbit:5672
    consumer:
      prefetch_count: 10

postgres:
  uri: postgresql://user:pass@localhost/blockatlas?sslmode=disable
  read_uri: postgresql://user:pass@localhost/blockatlas?sslmode=disable
  log: false

# [BNB] Binance DEX: https://wallet.binance.org
#       Binance Chain: https://explorer.binance.org
binance:
  api: http://localhost:3347/mock/binance-api
  explorer: http://localhost:3347/mock/binance-explorer

# [NIM] Nimiq: https://nimiq.com
nimiq:
  api: http://localhost:3347/mock/nimiq-rpc

# [XRP] Ripple: https://ripple.com
ripple:
  api: http://localhost:3347/mock/ripple-api

# [XLM] Stellar Lumen: https://www.stellar.org
stellar:
  api: http://localhost:3347/mock/stellar-api

# [KIN] Kin: https://www.kin.org
kin:
  api: http://localhost:3347/mock/kin-api

# [XTZ] Tezos: https://tezos.com
tezos:
  api: http://localhost:3347/mock/tezos-api
  rpc: https://mainnet.tezos.org.ua

# [ETH] Ethereum: https://ethereum.org
ethereum:
  api: http://localhost:3347/mock/eth-api
  blockbook_api: http://localhost:3347/mock/eth-blockbook-api
  collections_api: http://localhost:3347/mock/opensea-api
  collections_api_key: opensea_api_key
  rpc: http://localhost:3347/mock/eth-rpc

# [ETC] Ethereum Classic: https://ethereumclassic.org (Trust-Ray API)
classic:
  api: http://localhost:3347/mock/ethclassic-api

# [POA] POA Network: https://poa.network (Trust-Ray API)
poa:
  api: http://localhost:3347/mock/poa-api

# [CLO] Callisto Network: https://callisto.network (Trust-Ray API)
callisto:
  api: http://localhost:3347/mock/callisto-api

# [GO] GoChain: https://gochain.io (Trust-Ray API)
gochain:
  api: http://localhost:3347/mock/gochain-api

# [WAN] Wanchain: https://wanchain.org (Trust-Ray API)
# wanchain:
#   api: https://localhost:4567

# [TOMO] TomoChain: https://tomochain.com (Trust-Ray API)
tomochain:
  api: http://localhost:3347/mock/tomochain-api

# [TT] ThunderCore: https://www.thundercore.com (Trust-Ray API)
thundertoken:
  api: http://localhost:3347/mock/thundertoken-api

# [AION] Aion: https://aion.network
aion:
  api: http://localhost:3347/mock/aion-api

# [ICX] ICON: https://icon.foundation
icon:
  api: http://localhost:3347/mock/icon-api

# [TRX] Tron: https://tron.network/
tron:
  api: http://localhost:3347/mock/tron-api

# [VET] VeChain: https://www.vechain.org
vechain:
  api: http://localhost:3347/mock/vechain-api

# [THETA] THETA: https://www.thetatoken.org/
theta:
  api: http://localhost:3347/mock/theta-api

# [ATOM] Cosmos: https://cosmos.network/
cosmos:
  api: http://localhost:3347/mock/cosmos-api

# [ONTOLOGY] ONT: https://ont.io/
ontology:
  api: http://localhost:3347/mock/ontology-api

# [ZIL] Zilliqa: https://zilliqa.com
zilliqa:
  api: http://localhost:3347/mock/zilliqa-api
  # key: YOUR_API_KEY
  rpc: https://api.zilliqa.com

#[IoTeX] IoTeX: https://iotex.io
iotex:
  api: http://localhost:3347/mock/iotex-api

# [WAVES] Waves: http://wavesplatform.com
waves:
  api: http://localhost:3347/mock/waves-api

# [AE] Aeternity: https://aeternity.com
aeternity:
  api: http://localhost:3347/mock/aeternity-api

# [NAS] Nebulas: https://nebulas.io
nebulas:
  api: http://localhost:3347/mock/nebulas-api

fio:
  api: http://localhost:3347/mock/fio-api

# [BTC] Bitcoin: https://bitcoin.org/ (Blockbook API https://github.com/trezor/blockbook)
bitcoin:
  api: http://localhost:3347/mock/bitcoin-api

litecoin:
  api: http://localhost:3347/mock/litecoin-api

bitcoincash:
  api: http://localhost:3347/mock/bitcoincash-api

doge:
  api: http://localhost:3347/mock/doge-api

dash:
  api: http://localhost:3347/mock/dash-api

zcoin:
  api: http://localhost:3347/mock/zcoin-api

zcash:
  api: http://localhost:3347/mock/zcash-api

zelcash:
  api: http://localhost:3347/mock/zelcash-api

viacoin:
  api: http://localhost:3347/mock/viacoin-api

qtum:
  api: http://localhost:3347/mock/qtum-api

groestlcoin:
  api: http://localhost:3347/mock/groestlcoin-api

ravencoin:
  api: http://localhost:3347/mock/ravencoin-api

decred:
  api: http://localhost:3347/mock/decred-api

algorand:
  api: http://localhost:3347/mock/algorand-api

nano:
  api: http://localhost:3347/mock/nano-api

digibyte:
  api: http://localhost:3347/mock/digibyte-api

harmony:
  api: http://localhost:3347/mock/harmony-api

kava:
  api: http://localhost:3347/mock/kava-api

kusama:
  api: http://localhost:3347/mock/kusama-rpc
