version: '3.7'
services:
  market_api:
    container_name: market_api
    build:
      context: .
      args:
        - SERVICE=market_api
    ports:
    - 8421:8421
    links:
      - redis

  market_observer:
    container_name: market_observer
    build:
      context: .
      args:
      - SERVICE=market_observer
    links:
    - redis

  observer_api:
    container_name: observer_api
    build:
      context: .
      args:
        - SERVICE=observer_api
    ports:
      - 8422:8422
    links:
      - redis

  platform_api:
    container_name: platform_api
    build:
      context: .
      args:
        - SERVICE=platform_api
    ports:
    - 8420:8420

  swagger_api:
    container_name: swagger_api
    build:
      context: .
      args:
        - SERVICE=swagger_api
    ports:
      - 8423:8423

  platform_observer:
    build:
      context: .
      args:
        - SERVICE=platform_observer
    links:
      - redis

  redis:
    container_name: redis1
    image: neojt/mredis
    ports:
    - 6379:6379
