definitions:
  blockatlas.Collection:
    properties:
      address:
        type: string
      coin:
        type: integer
      description:
        type: string
      external_link:
        type: string
      id:
        type: string
      image_url:
        type: string
      name:
        type: string
      total:
        type: integer
    type: object
  blockatlas.CollectionPage:
    items:
      $ref: '#/definitions/blockatlas.Collection'
    type: array
  blockatlas.Delegation:
    properties:
      delegator:
        $ref: '#/definitions/blockatlas.StakeValidator'
        type: object
      metadata:
        type: object
      status:
        type: string
      value:
        type: string
    type: object
  blockatlas.DelegationResponse:
    properties:
      address:
        type: string
      balance:
        type: string
      coin:
        $ref: '#/definitions/coin.ExternalCoin'
        type: object
      delegations:
        $ref: '#/definitions/blockatlas.DelegationsPage'
        type: object
      details:
        $ref: '#/definitions/blockatlas.StakingDetails'
        type: object
    type: object
  blockatlas.DelegationsBatchPage:
    items:
      $ref: '#/definitions/blockatlas.DelegationResponse'
    type: array
  blockatlas.DelegationsPage:
    items:
      $ref: '#/definitions/blockatlas.Delegation'
    type: array
  blockatlas.DocsResponse:
    properties:
      docs:
        type: object
    type: object
  blockatlas.ResultsResponse:
    properties:
      docs:
        type: object
      total:
        type: integer
    type: object
  blockatlas.StakeValidator:
    properties:
      details:
        $ref: '#/definitions/blockatlas.StakingDetails'
        type: object
      id:
        type: string
      info:
        $ref: '#/definitions/blockatlas.StakeValidatorInfo'
        type: object
      status:
        type: boolean
    type: object
  blockatlas.StakeValidatorInfo:
    properties:
      description:
        type: string
      image:
        type: string
      name:
        type: string
      website:
        type: string
    type: object
  blockatlas.StakingDetails:
    properties:
      locktime:
        type: integer
      minimum_amount:
        type: string
      reward:
        $ref: '#/definitions/blockatlas.StakingReward'
        type: object
      type:
        type: string
    type: object
  blockatlas.StakingReward:
    properties:
      annual:
        type: number
    type: object
  coin.ExternalCoin:
    properties:
      coin:
        type: integer
      decimals:
        type: integer
      name:
        type: string
      symbol:
        type: string
    type: object
  endpoint.AddressBatchRequest:
    properties:
      address:
        type: string
      coin:
        type: integer
    type: object
  endpoint.AddressesRequest:
    items:
      $ref: '#/definitions/endpoint.AddressBatchRequest'
    type: array
  endpoint.ErrorDetails:
    properties:
      message:
        type: string
    type: object
  endpoint.ErrorResponse:
    properties:
      error:
        $ref: '#/definitions/endpoint.ErrorDetails'
        type: object
    type: object
  tokenindexer.Asset:
    properties:
      asset:
        type: string
      decimals:
        type: integer
      name:
        type: string
      symbol:
        type: string
      type:
        type: string
    type: object
  tokenindexer.Response:
    properties:
      assets:
        items:
          $ref: '#/definitions/tokenindexer.Asset'
        type: array
    type: object
info:
  contact: {}
  license: {}
paths:
  /v2/{coin}/blocks/{block}:
    get:
      consumes:
      - application/json
      description: Get Block information
      operationId: block_v2
      parameters:
      - default: zilliqa
        description: the coin name
        in: path
        name: coin
        required: true
        type: string
      - default: "850321"
        description: the query address
        in: path
        name: address
        required: true
        type: string
      produces:
      - application/json
      responses:
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/endpoint.ErrorResponse'
      summary: Get Block
      tags:
      - Transactions
  /v2/{coin}/staking/delegations/{address}:
    get:
      consumes:
      - application/json
      description: Get stake delegations from the address
      operationId: delegations
      parameters:
      - default: tron
        description: the coin name
        in: path
        name: coin
        required: true
        type: string
      - default: TPJYCz8ppZNyvw7pTwmjajcx4Kk1MmEUhD
        description: the query address
        in: path
        name: address
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/blockatlas.DelegationResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/endpoint.ErrorResponse'
      summary: Get Stake Delegations
      tags:
      - Staking
  /v2/{coin}/staking/validators:
    get:
      consumes:
      - application/json
      description: Get validators from the address
      operationId: validators_v2
      parameters:
      - default: cosmos
        description: the coin name
        in: path
        name: coin
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/blockatlas.DocsResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/endpoint.ErrorResponse'
      summary: Get Validators
      tags:
      - Staking
  /v2/{coin}/tokens/{address}:
    get:
      consumes:
      - application/json
      description: Get tokens from the address
      operationId: tokens
      parameters:
      - default: ethereum
        description: the coin name
        in: path
        name: coin
        required: true
        type: string
      - default: 0x5574Cd97432cEd0D7Caf58ac3c4fEDB2061C98fB
        description: the query address
        in: path
        name: address
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/blockatlas.CollectionPage'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/endpoint.ErrorResponse'
      summary: Get Tokens
      tags:
      - Transactions
  /v2/{coin}/transactions/{address}:
    get:
      consumes:
      - application/json
      description: Get transactions from the address
      operationId: tx_v2
      parameters:
      - default: tezos
        description: the coin name
        in: path
        name: coin
        required: true
        type: string
      - default: tz1WCd2jm4uSt4vntk4vSuUWoZQGhLcDuR9q
        description: the query address
        in: path
        name: address
        required: true
        type: string
      produces:
      - application/json
      responses:
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/endpoint.ErrorResponse'
      summary: Get Transactions
      tags:
      - Transactions
  /v2/{coin}/transactions/xpub/{xpub}:
    get:
      consumes:
      - application/json
      description: Get transactions from XPUB address
      operationId: tx_xpub_v2
      parameters:
      - default: bitcoin
        description: the coin name
        in: path
        name: coin
        required: true
        type: string
      - default: zpub6ruK9k6YGm8BRHWvTiQcrEPnFkuRDJhR7mPYzV2LDvjpLa5CuGgrhCYVZjMGcLcFqv9b2WvsFtY2Gb3xq8NVq8qhk9veozrA2W9QaWtihrC
        description: the xpub key
        in: path
        name: xpub
        required: true
        type: string
      produces:
      - application/json
      responses:
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/endpoint.ErrorResponse'
      summary: Get Transactions by XPUB
      tags:
      - Transactions
  /v2/staking/delegations:
    post:
      consumes:
      - application/json
      description: Get Stake Delegations for multiple coins
      operationId: staking_v2_batch
      parameters:
      - description: Validators addresses and coins
        in: body
        name: delegations
        required: true
        schema:
          $ref: '#/definitions/endpoint.AddressesRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/blockatlas.DelegationsBatchPage'
      summary: Get Multiple Stake Delegations
      tags:
      - Staking
  /v2/staking/list:
    post:
      consumes:
      - application/json
      description: Get Stake Delegations for multiple coins
      operationId: staking_v2
      parameters:
      - description: Validators addresses and coins
        in: body
        name: delegations
        required: true
        schema:
          $ref: '#/definitions/endpoint.AddressesRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/blockatlas.DelegationsBatchPage'
      summary: Get Multiple Stake Delegations
      tags:
      - Staking
  /v2/tokens:
    post:
      consumes:
      - application/json
      description: Get tokens
      operationId: tokens_v3
      parameters:
      - default: '{"60": ["0xb3624367b1ab37daef42e1a3a2ced012359659b0"]}'
        description: Payload
        in: body
        name: data
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/blockatlas.ResultsResponse'
      summary: 'Get list of tokens by map: coin -> [addresses]'
      tags:
      - Transactions
  /v3/staking/list:
    get:
      description: Get staking info by coin ID
      operationId: staking_v3
      parameters:
      - description: List of coins
        in: query
        name: coins
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/blockatlas.DelegationsBatchPage'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/endpoint.ErrorResponse'
      summary: Get staking info by coin ID
      tags:
      - Staking
  /v3/tokens/new:
    get:
      consumes:
      - application/json
      description: Get new tokens
      operationId: tokens_new_v3
      parameters:
      - description: unix timestamp
        in: query
        name: from
        required: true
        type: integer
      - description: coin like 60
        in: query
        name: coin
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/tokenindexer.Response'
      summary: Get list of new tokens by coin from specific unix timstamp
      tags:
      - Transactions
  /v4/{coin}/collections/{owner}/collection/{collection_id}:
    get:
      consumes:
      - application/json
      description: Get a collection from the address
      operationId: collection_v4
      parameters:
      - default: ethereum
        description: the coin name
        in: path
        name: coin
        required: true
        type: string
      - default: 0x0875BCab22dE3d02402bc38aEe4104e1239374a7
        description: the query address
        in: path
        name: owner
        required: true
        type: string
      - default: 0x06012c8cf97bead5deae237070f9587f8e7a266d
        description: the query collection
        in: path
        name: collection_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/blockatlas.CollectionPage'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/endpoint.ErrorResponse'
      summary: Get Collection
      tags:
      - Collections
  /v4/collectibles/categories:
    post:
      consumes:
      - application/json
      description: Get collection categories
      operationId: collection_categories_v4
      parameters:
      - default: '{"60": ["0xb3624367b1ab37daef42e1a3a2ced012359659b0"]}'
        description: Payload
        in: body
        name: data
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/blockatlas.DocsResponse'
      summary: Get list of collections from a specific coin and addresses
      tags:
      - Collections
swagger: "2.0"
